### ISSUE TITLE
Tree Shaking

### ISSUE THREAD

**Issue by lbenie** [dequelabs/react-axe#139] opened 2020-02-19 22:11 UTC
The library only uses `findDOMNode` from `ReactDOM` and we're required to load the whole module just to use one function

**Comment by straker** [comment] 2020-09-28 16:14
We have moved this package to be under our [axe-core-npm](https://github.com/dequelabs/axe-core-npm/) monorepo for easier management. As a result, this repository will be deprecated in the coming weeks. 

I believe this is a duplicate of #138, which found a resolution in the end so will close.

**Closed by straker** 2020-09-28 16:14 UTC
